print("My daily routine")
print("I wake up at 8 Am")
print("I brush my Teeth")
print("I take a bath")
print("I eat breakfase")
print("I read books")
print("I play with my sister")
print("I eat Lunch")
print("I do some painting")
print("I ride my bicycle")
print("I drink Milk")
print("I watch TV")
print("I eat dinner")
print("I brush my teeth")
print("I go to bed")
