print("Hi My name is reya and i would like Store my Friends Birthday")
Aditri=("02/09/2026")
Sana=("18/7/2026")
Ayesha=("14/7/2026")
Aaruni=("8/23/2026")
Ishani=("10/4/2026")
Devitha=("29/7/2026")

#Aditri=input("Aditri")
print("Aditris Birthday date is = ",Aditri)
print("Sanas birthday date is = ",Sana)
print("Ayeshas birthday date is = ",Ayesha)
print("Aarunisbirthday date is = ",Aaruni)
print("Ishanis birthdy date is = ",Ishani)
print("devithas birthday is on =" ,Devitha)